name: Readme Checker

on:
  pull_request:
     branches:
        - main

jobs:
  readmechecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if test -f README.md
          then
            echo "readme exists."
          else
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
          VALIDATE_PYTHON: true

