name: deploy

on:
  push:
     branches:
        - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
            echo "${{ secrets.KEYPAIR }}" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            ssh -i ~/.ssh/deploy_key ${{secrets.SERVERUSER}}@${{secrets.SERVER_HOST}} "cd ../docker-compose-flask-app && git pull && docker compose -d --build"
        

          


