name: Readme Checker

on:
  push:
     branches:
        - main

jobs:
  readmechecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if test -f README.md
          then
            echo "readme exists."
          else
            exit 1
          fi


