name: deploy

on:
  push:
     branches:
        - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
            ssh -i ${{secrets.KEYPAIR}} ${{secrets.SERVERUSER}}@${{secrets.SERVER_HOST}} "cd ../docker-compose-flask-app && git pull && docker compose -d --build"
        
        
          


